services:
  - type: web
    name: serveur-gps-medecin
    env: node
    buildCommand: npm install --include=dev && npm run build:css:all
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 18.0.0
